language: rust

env:
  - RUSTFLAGS="-D warnings"

before_script:
  - rustup component add rustfmt

matrix:
  fast_finish: true
  include:
    - rust: nightly
      os: linux
    - rust: nightly
      os: osx
    - rust: nightly-x86_64-pc-windows-msvc
      os: windows

script:
  - cargo fmt --all -- --check
  - cargo check --all --benches --bins --examples --tests
  - cargo test --all
  - cargo doc --features docs
